# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mathscoreprediction

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://testdockerd9.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_3278090b47cf44a4a80ac162ed967c0f }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0ba935bc9e764341bd3443d2e100c285 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: testdockerd9.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3278090b47cf44a4a80ac162ed967c0f }}/studentperformance:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mathscoreprediction'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_7856f93c3c3a48edb63abe46dc5d1b8e }}
        images: 'testdockerd9.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_3278090b47cf44a4a80ac162ed967c0f }}/studentperformance:${{ github.sha }}'